name: Update Backend
on:
  push:
    branches:
      - main
      - dev
env: 
  AWS_REGION: us-east-1
permissions: 
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v6
      - name: configure aws credentials for dev
        if: github.ref_name == 'dev'
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          role-to-assume: ${{ secrets.SERVICE_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: configure aws credentials for prod
        if: github.ref_name == 'main'
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          role-to-assume: ${{ secrets.PROD_SERVICE_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: install Terraform
        uses: hashicorp/setup-terraform@v4.0.0
      - name: build with Terraform
        env:
          TF_VAR_notification_email: ${{ secrets.NOTIFICATION_EMAIL }}
          STATE_BUCKET: ${{ github.ref_name == 'main' && secrets.PROD_STATE_BUCKET || secrets.DEV_STATE_BUCKET }}
        run: |
          cd terraform
          terraform init -backend-config="bucket=${STATE_BUCKET}"
          terraform apply -auto-approve
